

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './Components/Navbar'
import {CssBaseline} from '@mui/material';
import { GiDna2 } from "react-icons/gi";
import 'bootstrap/dist/css/bootstrap.min.css';
import FooterPage from './Components/Footer';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sahid Smriti Samudayiak Hospital',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
    <CssBaseline/>
      <body className={inter.className }>
        <NavBar/>

        {children}
        <FooterPage/>
        </body>
     
    </html>
  )
}
